### ISSUE TITLE
Calling methods directly on TV object in response to external event

### ISSUE THREAD

**Issue by readeral** [evandcoleman/node-appletv#10]
Hi Evan,

Sorry to raise this in an issue, but I'm hoping to get some clarity on how to use this library with emitted events.

I'm hoping to use this library in an event-driven environment (node red) and so am wanting to call AppleTV methods on a defined object rather than via a promise chain.

Given my limited understanding of Promises, it seems that I'd have to call scan() to kick off a promise chain every time I receive an event, which I'm hoping to avoid.

Would the following be the right way to go about instantiating an AppleTV object (opening a connection in the process while I can leverage off the promise chain)?

`let TV = return scan(uniqueIdentifier)
              .then(devices => {
                return devices[0].openConnection(credentials);
              })
              .then(device => {
                return device
              })

    example.on('input' function(command) {
      TV.sendKeyCommand(AppleTV.Key[command]);
    })  `

I realise I'll have to do something to handle the promise returned by sendKeyCommand (which I'm not yet sure how to do, but I'll work it out)

I'm not super great with promises, so trying to suss this out!

**Comment by readeral** [comment]
Ok, worked out something that works, whether or not it's elegant or has problems I'm not sure though. Would you care to review this for any pitfalls?:

`var atv = require('node-appletv');`

```
var TV;
    atv.scan(uniqueIdentifier)
      .then(devices => {
        TV = devices[0];
        return TV.openConnection(credentials);
      })
```
```
node.on('input', function(msg) {
      //TV.sendKeyCommand(Menu);
      TV.sendKeyCommand(atv.AppleTV.Key.Menu)
          .then(device => {
              console.log("Sent a menu command!");
          })
          .catch(error => {
              console.log(error);
          });
    });
```

**Comment by evandcoleman** [comment]
You can also do this with `await` calls. Please reopen if this is still an issue.
