### ISSUE TITLE
Cannot pair with AppleTV from MacOs

### ISSUE THREAD

**Issue by thorque** [evandcoleman/node-appletv#11]
Hi,

I am found your library and tried it out on my SmartHome RasbPi with Raspian installed. This works fine out of the box. Next try was the same but on the current MacOs 10.13.6.

But this doesn't work. The appletv pair command shows me the available AppleTs but cannot connect them. There is no error message, sometimes there is a timeout message.

Do I need to install or configure anything? The MacBool is in the same network.

Thanks
Thorsten

**Comment by evandcoleman** [comment]
Please try with the latest version 1.0.11
