### ISSUE TITLE
Cannot install on macOS High Sierra with homebrew node v10.12.0

### ISSUE THREAD

**Issue by Bluebie** [evandcoleman/node-appletv#13]
I've been trying to install it to support homebrew-theater-mode with no luck. I have an existing well functioning homebridge setup running on node v10.12.0

Attempts to `npm -g install homebridge-theater-mode` are failing with:

```
Error: make nodesodium exited with code null
    at ChildProcess.<anonymous> (/usr/local/lib/node_modules/node-appletv/node_modules/sodium/install.js:287:19)
```

Can this library just be switched on to tweetnacl instead of sodium? It seems like something a few people have issues installing. [TweetNaCl-js](https://github.com/dchest/tweetnacl-js) is a pure javascript implementation of NaCl, so it's a lot more portable, you maybe able to eliminate all compilation dependancy. It's a little slower, but i'm guessing for this application that's not important?

**Comment by GioCirque** [comment]
I think this is resolved by PR https://github.com/edc1591/node-appletv/pull/20

**Comment by evandcoleman** [comment]
Please try with 1.0.11.
