### ISSUE TITLE
Install fails on node_curve.cc compile

### ISSUE THREAD

**Issue by thedave42** [evandcoleman/node-appletv#30]
When I try to install node-appletv I'm getting an issue with one of the dependencies that causes the install to fail.  I've tried this on both a Windows 10 Home x64 machine and a MacOS 10.14.5 machine and get the same error.  

This is the install log from the Windows 10 machine:
[2019-06-25T01_53_39_250Z-debug.log](https://github.com/edc1591/node-appletv/files/3323222/2019-06-25T01_53_39_250Z-debug.log)

This is the log from the MacOS machine:
[2019-06-25T01_50_17_354Z-debug.log](https://github.com/edc1591/node-appletv/files/3323236/2019-06-25T01_50_17_354Z-debug.log)

**Comment by lewisthompson** [comment]
I'm hitting this too.  `node-appletv` has a package lock for `curve25519-n` of 1.1.3 which won't build for me with node v12.14.0.

Manually running `npm i curve25519-n` fetches 1.5.0 which builds but obviously this isn't helping my situation because of that package lock.

**Comment by evandcoleman** [comment]
Please try with 1.0.11.
