### ISSUE TITLE
Unable to install

### ISSUE THREAD

**Issue by PaRkThEcAr** [evandcoleman/node-appletv#31]
Hello all, i am having an issue installing Node AppleTV in macOS Mojave 10.14.6.

i have tried every solution here on this, the Homebridge Home Theater, and Homebridge Apple TV git projects.

when i ran a Yarn for this, this is the error i got.
`12 errors generated.
make: *** [Release/obj.target/curve/node_curve.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/Cellar/node/12.9.0/libexec/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:196:23)
gyp ERR! stack     at ChildProcess.emit (events.js:209:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
gyp ERR! System Darwin 18.2.0
gyp ERR! command "/usr/local/Cellar/node/12.9.0/bin/node" "/usr/local/Cellar/node/12.9.0/libexec/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/PaRkThEcAr1/node_modules/curve25519-n2
gyp ERR! node -v v12.9.0`

when i try to install Note-AppleTV using `sudo npm install -g node-appletv -unsafe--permissions
`
i get this error.

`> sodium@2.0.3 preinstall /usr/local/lib/node_modules/sodium
> node install.js --preinstall

Static libsodium was not found at /usr/local/lib/node_modules/sodium/deps/build/lib/libsodium so compiling libsodium from source.
glibtoolize:   error: Failed to create 'build-aux'
make: *** [libsodium] Error 1
/usr/local/lib/node_modules/sodium/install.js:287
            throw new Error(cmdLine + ' exited with code ' + code);
            ^

Error: make libsodium exited with code 2
    at ChildProcess.<anonymous> (/usr/local/lib/node_modules/sodium/install.js:287:19)
    at ChildProcess.emit (events.js:209:13)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! sodium@2.0.3 preinstall: `node install.js --preinstall`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the sodium@2.0.3 preinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/PaRkThEcAr1/.npm/_logs/2019-08-23T18_10_29_033Z-debug.log`

any help would be wonderful

**Comment by rjernigan** [comment]
Check out https://github.com/paixaop/node-sodium/issues/85#issuecomment-253053072

`brew install libtool autoconf automake`

**Comment by PaRkThEcAr** [comment]
> Check out [paixaop/node-sodium#85 (comment)](https://github.com/paixaop/node-sodium/issues/85#issuecomment-253053072)
> 
> `brew install libtool autoconf automake`

hello @rjernigan, so i actually already had these installed via homebrew. should i install node-sodium as well? the above comment is something everyone suggests you do, but it doesnt seem to work.

**Comment by evandcoleman** [comment]
Please try with 1.0.11.

**Comment by dannybster** [comment]
Hey there,

I'm still seeing this issue on latest 

iMac
MacOS Catalina 10.15.7 
XCode 11.3
Node versions tried: 
- 8.17.0
- 9.11.2
- 12.14.1

Is there any update?

**Comment by PaRkThEcAr** [comment]
Hey there! From what I gather, this project is dead. We use Node-Appletv-X these days (https://www.npmjs.com/package/node-appletv-x) it will work for most uses.

Let me know if that works out!

**Comment by evandcoleman** [comment]
Nope, not dead. I have a day job and do this work for free. I'd be happy to accept PRs here.

**Comment by dannybster** [comment]
> Hey there! From what I gather, this project is dead. We use Node-Appletv-X these days (https://www.npmjs.com/package/node-appletv-x) it will work for most uses. Let me know if that works out!
> […](#)
> Sent from my iPhone
> On Oct 18, 2020, at 10:38 AM, dannybster ***@***.***> wrote: ﻿ Hey there, I'm still seeing this issue on latest iMac MacOS Catalina 10.15.7 XCode 11.3 Node versions tried: 8.17.0 9.11.2 12.14.1 Is there any update? — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

Thanks for the tip I will check it out!



> Nope, not dead. I have a day job and do this work for free. I'd be happy to accept PRs here.

I really appreciate your hard work on this, I know it's not easy with a day job. If I solve the issue I'll be sure to come back and comment.
